[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"]}
tokio-tungstenite = "0.17"
tungstenite = "0.15"
futures = "0.3"
futures-util = "0.3"
dotenv = "0.15"
env_logger = "0.10"
log = "0.4"